backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: "/../"

collections:
  - name: "recipe"
    label: "Recipe"
    folder: "src/pages"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "image", label: "Image", widget: "image"}
      - { name: "tags", label: "Tags", widget: "list", field: {label: "Tag", name: "tag_name",widget: "string"}, default: ["Steak","Meat"]}
      - { name: "category", label: "Category", widget: "string", default: "Dinner"}
      - { name: "summary", label: "Summary", widget: "string", default: "This recipe is yummy"}
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "ingredients", label: "Ingredients", widget: "list",field: {label: "Ingredient", name: "ingredient_name",widget: "string"} }
      - { name: "path", label: "Path", widget: "string", pattern: [/], hint: "Path must start with /" }
